config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  get 'sales/create'
  root 'pages#home'
  resources :books do
    member do
      patch :refund
    end
  end
  resources :sales do
    member do
      patch :pay_author
      post :set_autopay
    end
  end
  # patch 'set_autopay/:id/:days', to: 'sales#set_autopay', as: :set_autopay_user
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :sales, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }

  scope :available, -> { where(available: true) }
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :book
  belongs_to :user

  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :copies, presence: true, numericality: { greater_than: 0 }

  def autopay(user_id)
    user = User.find(user_id)
    sales_to_pay = Sale.joins(book: :user).where(authorpayed: false, books: { user_id: user.id }).where('sales.created_at < ?', 7.days.ago)

    sales_to_pay.each do |sale|
      amount_to_pay = sale.price * user.author_cut
      user.update(balance: user.balance + amount_to_pay)
      sale.update(authorpayed: true, datedpayed: Time.now)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: %i[client author admin]
  enum membership: %i[free basic premium]
  after_initialize :set_default_value, if: :new_record?
  has_many :books, dependent: :destroy

  def set_default_value
    self.membership ||= :free
    self.role ||= :client
  end

  def author_cut
    case self.membership
    when 'free' then 0.05
    when 'basic' then 0.15
    when 'premium' then 0.25
    end
  end

  def payment
    return unless author?

    sales_to_pay = Sale.where(authordpayed: false)
                       .where('saledate <= ?', 7.days.ago)
                       .joins(book: :user)
                       .where('users.role = ?', 2)

    sales_to_pay.each do |sale|
      cut = case sale.book.user.membership
            when 'free' then 0.05
            when 'basic' then 0.15
            when 'premium' then 0.25
            end

      amount = sale.price * sale.copysold * cut
      sale.book.user.balance += amount
      sale.book.user.save!
      sale.update(authorpayed: true, datedpayed: Time.current)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :last_name, :email, :password, :role, :membership).tap do |params|
        params[:balance] = 300 if params[:role] == "client"
      end
    end

    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :last_name, :email, :password, :current_password, :role, :membership)
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.where(available: true).order('created_at DESC')
  end

  def new
    @book = Book.new
    @my_books = Book.where(user_id: current_user.id).order('created_at DESC')
    @sales = Sale.includes(:book).where(books: { user_id: current_user.id }, refund: false)
    @books_sold = @sales.where(refund: false).sum(:copies)
    @pending = @sales.where(authorpayed: false).sum(:copies)
  end

  def create
    return unless current_user.author?

    @book = Book.new(book_params)
    @book.user_id = current_user.id

    if @book.valid?
      @book.save
      redirect_back fallback_location: books_path, notice: 'Book Added'
    else
      flash.now[:alert] = 'Could not save book:'
      @book.errors.full_messages.each do |msg|
        flash.now[:alert] << "<br/>#{msg}"
      end
      render :new, status: 400
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to new_book_path, notice: 'Book updated successfully'
    else
      render :edit
    end
  end

  def refund
    sale = Sale.find(params[:id])
    author = sale.book.user
    client = sale.user

    author.update(balance: author.balance - (sale.price * author.author_cut)) if sale.authorpayed?
    client.update(balance: client.balance + sale.price)
    sale.update(refund: true)

    redirect_to new_book_path, notice: 'Book refund successfully'
  end

  private

  def book_params
    params.require(:book).permit(:user, :title, :description, :price, :available)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to new_sale_path if user_signed_in? && current_user.client?
    redirect_to new_book_path if user_signed_in? && current_user.author?
    redirect_to sales_path if user_signed_in? && current_user.admin?
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  def new
    @books = Book.where(available: true).order('created_at DESC')
    @my_books = Sale.where(user_id: current_user.id, refund: false).order('created_at DESC').sum(:copies)
    @sale = Sale.new
  end

  def index
    @sales = Sale.includes(:book, :user).where(refund: false).order('created_at DESC')
    @users = User.where(role: %w[client author]).order('created_at DESC')
  end

  def create
    book = Book.find(params[:sale][:book_id])
    copies = params[:sale][:quantity].to_i
    price = book.price * copies

    if current_user.balance < price
      redirect_to new_sale_path, alert: 'You do not have enough balance to purchase this book.'
      return
    end

    sale = Sale.new(book:, user: current_user, price:, copies:)

    if sale.save
      current_user.update(balance: current_user.balance - price)
      book.update(amountsold: book.amountsold + copies)
      redirect_to new_sale_path, notice: 'Book purchased successfully'
    else
      redirect_to new_sale_path, alert: 'Unable to purchase book'
    end
  end

  def pay_author
    @sale = Sale.find(params[:id])
    @author = @sale.book.user
    @author.update(balance: @author.balance + (@sale.price * @author.author_cut))
    @sale.update(authorpayed: true, datedpayed: Time.now)
    redirect_to sales_path, notice: 'Author paid successfully'
  end

  def set_autopay
    @author = User.find(params[:id])
    @author.update(autopay_days: params[:days])

    # Schedule the job to run every X days
    AutopayAuthorJob.perform_at(10.seconds.from_now, @author.id)

    redirect_to sales_path, notice: 'Autopay set successfully'
  end

  def autopay(user_id)
    user = User.find(user_id)
    sales_to_pay = Sale.joins(book: :user).where(authorpayed: false, books: { user_id: user.id }).where('sales.created_at < ?', 7.days.ago)

    sales_to_pay.each do |sale|
      amount_to_pay = sale.price * user.author_cut
      user.update(balance: user.balance + amount_to_pay)
      sale.update(authorpayed: true, datedpayed: Time.now)
    end

    redirect_to sales_path, notice: 'Autopay completed successfully'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/books/edit.html.erb
<h1>Edit book <%=@book.title%></h1>

<%= form_for @book do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :available %>
    <%= f.check_box :available %>
  </div>
  
  <%= f.submit "Update Book" %>
<% end %>

app/views/books/new.html.erb
<h1>Add a new book</h1>

<div class="notice"><%= notice %></div>
<% if @book.errors.any? %>
  <div>
    <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @book do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :price %>
  <%= f.number_field :price, step: 0.01 %>

  <%= f.submit "Add Book" %>
<% end %>

<br/>

<h1>My Books</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th>Copies sold</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @my_books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.description %></td>
        <td><%= book.price %></td>
        <td><%= book.amountsold %></td>
        <td><%= link_to "Edit", edit_book_path(book) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h1>My Sales</h1>

<table>
  <thead>
    <tr>
      <th>Book Title</th>
      <th>Price</th>
      <th>Copies</th>
      <th>User</th>
      <th>Paid</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.book.title %></td>
        <td><%= number_to_currency(sale.price) %></td>
        <td><%= sale.copies %></td>
        <td><%= sale.user.email %></td>
        <td><%= sale.authorpayed ? "Yes" : "No" %></td>
        <td><%= button_to "Refund", refund_book_path(sale), method: :patch %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<p>
  <strong>Balance:</strong>
  <%= "$#{current_user.balance}" %>
  <br/>
  <strong>Books Sold:</strong>
  <%= @books_sold%>
  <br/>
  <strong>Books pending payment:</strong>
  <%= @pending%>
  <%= button_to  'Logout', destroy_user_session_path, method: :delete%>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LosMejoresLibros</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Los Mejores Libros</h1>
<% if current_user %>
  <p>
    Welcome, <%= current_user.email %>
  </p>
  <p>
    You are logged in as <%= current_user.role %> 
    <br/>
    Your membership is <%= current_user.membership %>
  </p>
  <%= link_to 'Logout', destroy_user_session_path, 'data-turbo-method': :delete %>

<% else %>
  <p>
    You are not logged in.
  </p>
  <%= link_to 'Sign up', new_user_registration_path %>
  <br/>
  <%= link_to 'Login', new_user_session_path %>
<% end %>

app/views/sales/index.html.erb
<h1>Sales</h1>
<br/>
<div class="notice"><%= notice %></div>
<div class="alert"><%= alert %></div>
<br/>
<table>
  <thead>
    <tr>
      <th>Book Title</th>
      <th>Price</th>
      <th>Copies</th>
      <th>User</th>
      <th>Author Paid</th>
      <th>Date Paid</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.book.title %></td>
        <td><%= number_to_currency(sale.price) %></td>
        <td><%= sale.copies %></td>
        <td><%= sale.user.email %></td>
        <td><%= sale.authorpayed ? "Yes" : "No" %></td>
        <td><%= sale.datedpayed %></td>
        <td>
          <% unless sale.authorpayed %>
            <%= button_to "Pay Author", pay_author_sale_path(sale), method: :patch %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br/>
<h1>Users</h1>
<br/>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>role</th>
      <th>Balance</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <td><%= number_to_currency(user.balance) %></td>
        <% if user.author? %>
          <td>
            <%= form_tag set_autopay_sale_path(user), method: :post, class: "autopay-form" do %>
              <%= label_tag :days, "Days" %>
              <%= number_field_tag :days, 7, min: 1, class: "form-control" %>
              <%= submit_tag "Set Auto Pay", class: "btn btn-primary" %>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<%if current_user.admin?%>
  <%= button_to 'Monitor Jobs', sidekiq_web_path, method: :get%>
<%end%>
<br/>
<%= button_to  'Logout', destroy_user_session_path, method: :delete%>

app/views/sales/new.html.erb
<h1>Buy Books</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= "#{book.user.name} #{book.user.last_name}" %></td>
        <td><%= "$#{book.price}" %></td>
        <%= form_for Sale.new do |f| %>
          <td><%= f.number_field :quantity, value: 1, min: 1 %></td>
          <td><%= f.submit 'Buy' %></td>
          <%= f.hidden_field :book_id, value: book.id %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="notice"><%= notice %></div>
<div class="alert"><%= alert %></div>
<br/>
<p>
  <strong>Balance:</strong>
  <%= "$#{current_user.balance}" %>
  <br/>
  <strong>Books own:</strong>
  <%= @my_books %>
  <%= button_to  'Logout', destroy_user_session_path, method: :delete%>
</p>